### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [lknix/zsh-theme-minimalx#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by lknix** [comment]
Hi @unixorn! Thanks for consideration - I've updated and added a screenshot to the README. Let me know if you need anything else.

**Comment by unixorn** [comment]
Added it to the list, thanks!
